version: "2"

services:
  vote:
    image: hanbzskyvotingapp_vote
    command: python app.py
    ports:
      - "5000:80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    image: hanbzsky/votingapp_worker

  db:
    image: postgres:9.4

  result:
    image: hanbzsky/votingapp_result
    ports:
      - "5001:80"
      - "5858:5858"
